###################################################################

# Created by write_sdc on Sun Jan 13 21:37:25 2019

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions slow_1v08c125 -library slow_1v08c125
set_wire_load_model -name ForQA -library slow_1v08c125
set_max_area 0
set_load -pin_load 3 [get_ports XOUT]
set_load -pin_load 3 [get_ports DATA_7]
set_load -pin_load 3 [get_ports DATA_6]
set_load -pin_load 3 [get_ports DATA_5]
set_load -pin_load 3 [get_ports DATA_4]
set_load -pin_load 3 [get_ports DATA_3]
set_load -pin_load 3 [get_ports DATA_2]
set_load -pin_load 3 [get_ports DATA_1]
set_load -pin_load 3 [get_ports DATA_0]
set_load -pin_load 3 [get_ports POS_1]
set_load -pin_load 3 [get_ports POS_0]
set_load -pin_load 3 [get_ports SEG_6]
set_load -pin_load 3 [get_ports SEG_5]
set_load -pin_load 3 [get_ports SEG_4]
set_load -pin_load 3 [get_ports SEG_3]
set_load -pin_load 3 [get_ports SEG_2]
set_load -pin_load 3 [get_ports SEG_1]
set_load -pin_load 3 [get_ports SEG_0]
set_load -pin_load 3 [get_ports FLAG]
set_load -pin_load 3 [get_ports ENC_DEC]
set_load -pin_load 3 [get_ports KEY_LEN]
set_load -pin_load 3 [get_ports PHASE_2]
set_load -pin_load 3 [get_ports PHASE_1]
set_load -pin_load 3 [get_ports PHASE_0]
create_clock [get_ports XIN]  -period 10  -waveform {0 5}
set_input_delay -clock XIN  -max 2  [get_ports XIN]
set_input_delay -clock XIN  -min 0  [get_ports XIN]
set_input_delay -clock XIN  -max 2  [get_ports DATA_1]
set_input_delay -clock XIN  -min 0  [get_ports DATA_1]
set_input_delay -clock XIN  -max 2  [get_ports DATA_2]
set_input_delay -clock XIN  -min 0  [get_ports DATA_2]
set_input_delay -clock XIN  -max 2  [get_ports DATA_3]
set_input_delay -clock XIN  -min 0  [get_ports DATA_3]
set_input_delay -clock XIN  -max 2  [get_ports DATA_4]
set_input_delay -clock XIN  -min 0  [get_ports DATA_4]
set_input_delay -clock XIN  -max 2  [get_ports DATA_5]
set_input_delay -clock XIN  -min 0  [get_ports DATA_5]
set_input_delay -clock XIN  -max 2  [get_ports DATA_6]
set_input_delay -clock XIN  -min 0  [get_ports DATA_6]
set_input_delay -clock XIN  -max 2  [get_ports DATA_7]
set_input_delay -clock XIN  -min 0  [get_ports DATA_7]
set_input_delay -clock XIN  -max 2  [get_ports RST]
set_input_delay -clock XIN  -min 0  [get_ports RST]
set_input_delay -clock XIN  -max 2  [get_ports CLK]
set_input_delay -clock XIN  -min 0  [get_ports CLK]
set_input_delay -clock XIN  -max 2  [get_ports DATA_0]
set_input_delay -clock XIN  -min 0  [get_ports DATA_0]
set_output_delay -clock XIN  -max 2  [get_ports DATA_1]
set_output_delay -clock XIN  -min 0  [get_ports DATA_1]
set_output_delay -clock XIN  -max 2  [get_ports DATA_2]
set_output_delay -clock XIN  -min 0  [get_ports DATA_2]
set_output_delay -clock XIN  -max 2  [get_ports DATA_3]
set_output_delay -clock XIN  -min 0  [get_ports DATA_3]
set_output_delay -clock XIN  -max 2  [get_ports DATA_4]
set_output_delay -clock XIN  -min 0  [get_ports DATA_4]
set_output_delay -clock XIN  -max 2  [get_ports DATA_5]
set_output_delay -clock XIN  -min 0  [get_ports DATA_5]
set_output_delay -clock XIN  -max 2  [get_ports DATA_6]
set_output_delay -clock XIN  -min 0  [get_ports DATA_6]
set_output_delay -clock XIN  -max 2  [get_ports DATA_7]
set_output_delay -clock XIN  -min 0  [get_ports DATA_7]
set_output_delay -clock XIN  -max 2  [get_ports DATA_0]
set_output_delay -clock XIN  -min 0  [get_ports DATA_0]
set_output_delay -clock XIN  -max 2  [get_ports FLAG]
set_output_delay -clock XIN  -min 0  [get_ports FLAG]
set_output_delay -clock XIN  -max 2  [get_ports KEY_LEN]
set_output_delay -clock XIN  -min 0  [get_ports KEY_LEN]
set_output_delay -clock XIN  -max 2  [get_ports SEG_0]
set_output_delay -clock XIN  -min 0  [get_ports SEG_0]
set_output_delay -clock XIN  -max 2  [get_ports SEG_1]
set_output_delay -clock XIN  -min 0  [get_ports SEG_1]
set_output_delay -clock XIN  -max 2  [get_ports SEG_2]
set_output_delay -clock XIN  -min 0  [get_ports SEG_2]
set_output_delay -clock XIN  -max 2  [get_ports SEG_3]
set_output_delay -clock XIN  -min 0  [get_ports SEG_3]
set_output_delay -clock XIN  -max 2  [get_ports SEG_4]
set_output_delay -clock XIN  -min 0  [get_ports SEG_4]
set_output_delay -clock XIN  -max 2  [get_ports SEG_5]
set_output_delay -clock XIN  -min 0  [get_ports SEG_5]
set_output_delay -clock XIN  -max 2  [get_ports XOUT]
set_output_delay -clock XIN  -min 0  [get_ports XOUT]
set_output_delay -clock XIN  -max 2  [get_ports SEG_6]
set_output_delay -clock XIN  -min 0  [get_ports SEG_6]
set_output_delay -clock XIN  -max 2  [get_ports POS_0]
set_output_delay -clock XIN  -min 0  [get_ports POS_0]
set_output_delay -clock XIN  -max 2  [get_ports POS_1]
set_output_delay -clock XIN  -min 0  [get_ports POS_1]
set_output_delay -clock XIN  -max 2  [get_ports ENC_DEC]
set_output_delay -clock XIN  -min 0  [get_ports ENC_DEC]
set_output_delay -clock XIN  -max 2  [get_ports PHASE_0]
set_output_delay -clock XIN  -min 0  [get_ports PHASE_0]
set_output_delay -clock XIN  -max 2  [get_ports PHASE_1]
set_output_delay -clock XIN  -min 0  [get_ports PHASE_1]
set_output_delay -clock XIN  -max 2  [get_ports PHASE_2]
set_output_delay -clock XIN  -min 0  [get_ports PHASE_2]
set_input_transition -max 0.5  [get_ports XIN]
set_input_transition -min 0.5  [get_ports XIN]
set_input_transition -max 0.5  [get_ports CLK]
set_input_transition -min 0.5  [get_ports CLK]
set_input_transition -max 0.5  [get_ports RST]
set_input_transition -min 0.5  [get_ports RST]
set_input_transition -max 0.5  [get_ports DATA_7]
set_input_transition -min 0.5  [get_ports DATA_7]
set_input_transition -max 0.5  [get_ports DATA_6]
set_input_transition -min 0.5  [get_ports DATA_6]
set_input_transition -max 0.5  [get_ports DATA_5]
set_input_transition -min 0.5  [get_ports DATA_5]
set_input_transition -max 0.5  [get_ports DATA_4]
set_input_transition -min 0.5  [get_ports DATA_4]
set_input_transition -max 0.5  [get_ports DATA_3]
set_input_transition -min 0.5  [get_ports DATA_3]
set_input_transition -max 0.5  [get_ports DATA_2]
set_input_transition -min 0.5  [get_ports DATA_2]
set_input_transition -max 0.5  [get_ports DATA_1]
set_input_transition -min 0.5  [get_ports DATA_1]
set_input_transition -max 0.5  [get_ports DATA_0]
set_input_transition -min 0.5  [get_ports DATA_0]
